version: '3.8'

services:
  postgres:
    image: postgres
    container_name: fenix_data
    environment:
      POSTGRES_DB: fenix
      POSTGRES_USER: fenixfire
      POSTGRES_PASSWORD: deluxefenixfire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

